@startuml
class ChangeColorSpaceRequest {
    - ICC_Profile iccProfile
    - ICC_ColorSpace cmykColorSpace
    + ChangeColorSpaceRequest()
}
class PDFFile {
}
ChangeColorSpaceRequest --|> PDFFile
@enduml